<div class="customheader">
    <div class="header content">
        <div class="logomarca">
            <?php echo $this->getChildHtml("logo"); ?>
        </div>
        <div class="busca">
           <?php echo $this->getChildHtml("search-header"); ?>
        </div>
        <div class="toplogin">
            <span class="tl-icon"></span>
            <span class="tl-text"><a href="#">Faça login ou Cadastre-se!</a></span>
        </div>
        <div class="carrinho">
            <?php echo $this->getChildHtml("minicart"); ?>
        </div>
    
    </div>
</div>